### PR TITLE
Refactor Dockerfile

### PR DESCRIPTION
**Pull request by Gauvino**
- Changed emsdk version to the latest one from 2.0.34 to 3.1.51
- Re-arranged the package
- Added clean command

### CODE REVIEW

**Comment by Gauvino** [comment]
image
Proof of building

**Comment by Gauvino** [comment]
@dmitrylyzo does this PR is needed or can be closed ?

The repo is abandoned ?

**Comment by dmitrylyzo** [comment]
I don't remember where I stopped.
IIRC, updating Emscripten to latest was causing JSO to not work in older browsers (TV).
Moreover, it requires more changes: https://github.com/jellyfin/JavascriptSubtitlesOctopus/compare/master...dmitrylyzo:JavascriptSubtitlesOctopus:update-emscripten

The idea was to update this repo to upstream (as clean as possible, but without unnecessary changes).
One of those updates: https://github.com/jellyfin/JavascriptSubtitlesOctopus/pull/46

10.9 has moved to JASSUB, so this repo has become less relevant.

**Comment by Gauvino** [comment]
> I don't remember where I stopped.
> 
> IIRC, updating Emscripten to latest was causing JSO to not work in older browsers (TV).
> 
> Moreover, it requires more changes: https://github.com/jellyfin/JavascriptSubtitlesOctopus/compare/master...dmitrylyzo:JavascriptSubtitlesOctopus:update-
> 
> 
Ok, I didn't see this change.
> 
> The idea was to update this repo to upstream (as clean as possible, but without unnecessary changes).
> 
> One of those updates: https://github.com/jellyfin/JavascriptSubtitlesOctopus/pull/46
> 
> 
> 
> 10.9 has moved to JASSUB, so this repo has become less relevant.
> 
> 
>
So this PR is not needed anymore if this repo is being used this jellyfin switch to jassub

**Pull request closed without merging**
