### PR TITLE
Add support for legacy browsers like found in some SmartTVs

### PR DESCRIPTION
**Pull request by JustAMan**
Also includes a workaround for a bug found in WebOS 1.2 app engine (checked in emulator)

### CODE REVIEW

**Review by EraYaN — APPROVED** [review]
Looks good, can't test it on an old enough browser version though currently.

**Comment by EraYaN** [comment]
Is there a reason this one is forked two levels deep?

**Comment by dkanada** [comment]
I had originally forked the main one, but then I realized I could just fork the copy @JustAMan made and avoid any pull requests. Alas, he didn't make his changes on master so we still had to deal with the pull request and now we're too invested in this fork to switch to the main one.

**Comment by EraYaN** [comment]
So if we have upstreamed everything we could technically refork directly into jellyfin correct?

**Comment by dkanada** [comment]
Well, if the changes ever get merged upstream I would just use that repository instead of keeping our own custom fork.

**Comment by JustAMan** [comment]
Yeah, I think we'll dump this repo when (or if) they take my fixes.

**Pull request merged**
